### PR TITLE
MUMMNG-1308: Update style guide to document sentence case

### PR DESCRIPTION
**Pull request by jhanstra**
image

### CODE REVIEW

**Comment by keirserrie** [comment]
Would like to broaden use of sentence case beyond widget buttons unless you guys have objections--

Use title case for app titles. Use sentence case everywhere else (e.g., button text).

**Comment by jhanstra** [comment]
Sounds good to me @keirserrie. We might need a separate JIRA issue to go back and make sure all of our buttons meet that criteria.

**Comment by keirserrie** [comment]
Cool @apetro you good w/that?

**Comment by jhanstra** [comment]
@keirserrie what do you think about this wording? Look good to you?

Text inside widgets, including the action button at the bottom, should always be in sentence case, i.e. "See all course services" rather than "See all Course Services". Widget titles should be in title case, i.e. "Course Services".

**Comment by keirserrie** [comment]
:+1:  looks good

**Pull request merged**
